[versions]
kaml = "0.55.0"
json = "1.6.0"
slf4j = "2.0.9"
kotest = "5.7.2"
exposed = "0.44.1"
sqlite = "3.43.2.2"
ikonli = "12.2.0"
commons-csv = "1.10.0"
jieba = "1.0.0"

# Plugin versions
detekt = "1.23.3"
javafxplugin = "0.1.0"
badassruntime = "1.13.0"

[libraries]
kaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kaml" }
json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "json" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j" }

kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-framework-datatest = { group = "io.kotest", name = "kotest-framework-datatest", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }

ikonli-javafx = { group = "org.kordamp.ikonli", name = "ikonli-javafx", version.ref = "ikonli" }
ikonli-material2 = { group = "org.kordamp.ikonli", name = "ikonli-material2-pack", version.ref = "ikonli" }

apache-commons-csv = { group = "org.apache.commons", name = "commons-csv", version.ref = "commons-csv" }

jieba = { group = "com.github.huaban", name = "jieba-analysis", version.ref = "jieba" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafxplugin" }
badassruntime = { id = "org.beryx.runtime", version.ref = "badassruntime" }